config/routes.rb
Rails.application.routes.draw do
  

  root to: 'voters#index'
  resources :voters, param: :cnp
  resources :alerts
  devise_for :users, :controllers => { registrations: 'registrations' }

  get '/showvoters' => 'voters#showvoters'
  post '/votetime' => 'voters#votetime'

  get '/alertshall' => 'voters#alertshall'
  get '/representatives' => 'voters#representatives'
  get '/statistics' => 'voters#statistics'
  get '/voternotfound' => 'voters#voternotfound'

  post 'search_voter' => 'voters#search_voter'
  post 'create_alert' => 'voters#create_alert'
  post 'double_voting' => 'voters#double_voting'
end

app/models/alert.rb
class Alert < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :voters

  
  	#@fields = %w[Territory BEC]
  	#validates :field, :inclusion => @fields

  
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  belongs_to :user
  self.primary_key = 'cnp'

  #def to_param
  #  cnp.parameterize
  #end

end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @alerts = Alert.all
    respond_with(@alerts)
  end

  def show
    respond_with(@alert)
  end

  def new
    @alert = Alert.new
    respond_with(@alert)
  end

  def edit
  end

  def create
    @alert = Alert.new(alert_params)
    @alert.save
    #@cnp_id = params[:cnp_now].to_i

    #puts "^^^^^^^^^^^^^^^^^^^^^^^"
    #puts @cnp_id

    redirect_to showvoters_path
  end

  def update
    @alert.update(alert_params)
    respond_with(@alert)
  end

  def destroy
    @alert.destroy
    respond_with(@alert)
  end

  private
    def set_alert
      @alert = Alert.find(params[:id])
    end

    def alert_params
      params.require(:alert).permit(:description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :field, :voting_section)
  end
 
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :field, :voting_section)
  end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  before_action :set_voter, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @voters = Voter.all
    
    if session[:found_voter].is_a? Integer

      @cnp_voter = session[:found_voter]

    else
      @found_voter = nil

    end

    session[:new_vote_validation] = false

    respond_with(@voters)
  end

  def show
    respond_with(@voter)
  end

  def new
    @voter = Voter.new
    respond_with(@voter)
  end

  def edit
  end

  def create
    @voter = Voter.new(voter_params)
    @voter.save
    respond_with(@voter)
  end

  def update
    @voter.update(voter_params)
    respond_with(@voter)
  end

  def destroy
    @voter.destroy
    respond_with(@voter)
  end

  def voternotfound
    render voternotfound_path
  end

  def search_voter

    n = params[:cnp].to_i
    
    if Voter.all.where("cnp is ?", n).size != 0 then
      session[:found_voter] = Voter.find(params[:cnp]).cnp.to_i
      redirect_to voters_path
    else
      redirect_to voternotfound_path
    end    
  end

  def showvoters
    
    @cnp_id = params[:cnp].to_i


    puts @cnp_id

    @voter = Voter.find(@cnp_id)

    @alert = Alert.new
  

    render '/showvoters'
  end

  def votetime

    @voter = Voter.find(params[:cnp])
    @voter.update({:user_id => current_user.id})
    session[:new_vote_validation] = false
    
    redirect_to showvoters_path(:cnp => @voter.cnp)
  end


  def create_alert


    @alert = Alert.new
    @alert.description = params[:description]
    @alert.voter_cnp = params[:voter_cnp]
    @alert.current_user_id = params[:current_user_id]
    @alert.user_id = params[:user_id]
    @alert.time = params[:time]
    @alert.save

    @voter = Voter.find(@alert.voter_cnp)

    @voter.update({:user_id=>nil})


    redirect_to showvoters_path(:cnp => @alert.voter_cnp)
  end

  def double_voting
    session[:new_vote_validation] = true

    redirect_to showvoters_path(:cnp => params[:cnp])
  end

  def representatives
    @territory_users = User.all.where("field is ?", "Territory")
    render '/representatives'
  end

  def alertshall
    @all_alerts = Alert.all
    @all_voters = Voter.all
    @all_users = User.all.where("field is ?", "Territory")
    @alertscnp = Alert.all.group("voter_cnp")
    @alertsuser = Alert.all.group("user_id")
    
    render '/alertshall'
  end 

  def percentofall(x)
    (x.size * 100.0 / @allvoters.size).round(2)
  end

  def vpercentofall(x, y)
    if y.size != 0 then
      (x.size * 100.0 / y.size).round(2)
    else
      100.0
    end
  end

  def statistics
    @allvoters = Voter.all

    @listyoung = Array.new
    @listavg = Array.new
    @listold = Array.new

    @allvoters.each do |voter|
      l = voter.cnp.to_s[1..2].to_i
      if (l <= 96 && l >= 84) then
        @listyoung << voter
      elsif (l <= 83 && l >= 54) then
        @listavg << voter
      elsif (l < 53) then
        @listold << voter
      end
    end

    @percentlistyoung = percentofall(@listyoung)
    @percentlistavg = percentofall(@listavg)
    @percentlistold = percentofall(@listold)


    @listmen = Voter.all.where("cnp like ?", '1%')
    @percentlistmen = percentofall(@listmen)
    @listwomen = Voter.all.where("cnp like ?", '2%')
    @percentlistwomen = percentofall(@listwomen)

    @listrural = Voter.all.where("lower(zone) is ?", 'rural')
    @percentlistrural = percentofall(@listrural)
    @listurban = Voter.all.where("lower(zone) is ?", 'urban')
    @percentlisturban = percentofall(@listurban)

    @listbuc = Voter.all.where("lower(address) is ?", 'bucuresti')
    @percentlistbuc = percentofall(@listbuc)
    @listtim = Voter.all.where("lower(address) is ?", 'timisoara')
    @percentlisttim = percentofall(@listtim)
    @listbad = Voter.all.where("lower(address) is ?", 'badesti')
    @percentlistbad = percentofall(@listbad)
    @listros = Voter.all.where("lower(address) is ?", 'rosieni')
    @percentlistros = percentofall(@listros)

    @listvoters = Voter.all.where("user_id is not null")
    @percentlistvoters = percentofall(@listvoters)

    @vlistyoung = @listyoung.select{|voter| voter.user_id}
    @vlistavg = @listavg.select{|voter| voter.user_id}
    @vlistold = @listold.select{|voter| voter.user_id}

    @vpercentlistyoung = vpercentofall(@vlistyoung, @listyoung)
    @vpercentlistavg = vpercentofall(@vlistavg, @listavg)
    @vpercentlistold = vpercentofall(@vlistold, @listold)


    @vlistmen = @listmen.select{|voter| voter.user_id}
    @vpercentlistmen = vpercentofall(@vlistmen, @listmen)
    @vlistwomen = @listwomen.select{|voter| voter.user_id}
    @vpercentlistwomen = vpercentofall(@vlistwomen, @listwomen)

    @vlistrural = @listrural.select{|voter| voter.user_id}
    @vpercentlistrural = vpercentofall(@vlistrural, @listrural)
    @vlisturban = @listurban.select{|voter| voter.user_id}
    @vpercentlisturban = vpercentofall(@vlisturban, @listurban)

    @vlistbuc = @listbuc.select{|voter| voter.user_id}
    @vpercentlistbuc = vpercentofall(@vlistbuc, @listbuc)
    @vlisttim = @listtim.select{|voter| voter.user_id}
    @vpercentlisttim = vpercentofall(@vlisttim, @listtim)
    @vlistbad = @listbad.select{|voter| voter.user_id}
    @vpercentlistbad = vpercentofall(@vlistbad, @listbad)
    @vlistros = @listros.select{|voter| voter.user_id}
    @vpercentlistros = vpercentofall(@vlistros, @listros)

    render '/statistics'
  end

  private
    def set_voter
      @voter = Voter.find(params[:cnp])
    end

    def voter_params
      params.require(:voter).permit(:cnp, :last_name, :first_name, :address, :zone, :user_id)
    end

    def set_alert
      @alert = Alert.find(params[:id])
    end

    def alert_params
      params.require(:alert).permit(:description, :voter_cnp, :user_id, :current_user_id, :time)
    end

end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h1>Listing alerts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= alert.description %></td>
        <td><%= link_to 'Show', alert %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert', new_alert_path %>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @alert.description %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SISTEMUL DE VALIDARE ELECTRONICA A VOTURILOR</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="title">
<h1> 
SISTEMUL DE VALIDARE ELECTRONICA A VOTURILOR 
</h1>
<br>
<% if user_signed_in? %> 
	<div id="login"> 
		logged in as : <strong><%= current_user.email %></strong> <!-- current_username is a DEVISE parameter --> 
		<%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
	</div>

<% end %>

</div>

<div id='application'>
	<%= yield %>
</div>

</body>
</html>

app/views/voters/_bec.html.erb
<div class="content">
<h2>
<%= link_to 'Alerts', alertshall_path %>
<br> 
<br> 
<%= link_to 'Representatives', representatives_path %>
<br>  
<br> 
<%= link_to 'Statistics', statistics_path %>
</h2>
</div> 

app/views/voters/_form.html.erb
<%= form_for(@voter) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cnp %><br>
    <%= f.number_field :cnp %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :zone %><br>
    <%= f.text_field :zone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voters/_territory.html.erb
<div class="content">
<% session[:found_voter] = nil %>
<%= form_tag search_voter_path do %>
<p>
<%= text_field_tag :cnp, params[:cnp] %>
<%= submit_tag "Search Voter", :class => "button" %>
</p>
<% end %>


<% if @cnp_voter == nil%>
<p class="app_text"> Insert Voter CNP </p>

<% else %>


<p class="app_text"> CNP was identified: <%= @voters.find(@cnp_voter).cnp %> </p>
<div class="app_link"><%= link_to 'Validate', showvoters_path(:cnp => @voters.find(@cnp_voter).cnp) %></div>
<% end %>

</div>

app/views/voters/edit.html.erb
<h1>Editing voter</h1>

<%= render 'form' %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<% if current_user.field == 'Territory' %>
  <%= render 'territory' %>
<% elsif current_user.field == 'BEC' %>
  <%= render 'bec' %>
<% end %>

app/views/voters/new.html.erb
<h1>New voter</h1>

<%= render 'form' %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cnp:</strong>
  <%= @voter.cnp %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @voter.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @voter.first_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @voter.address %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @voter.zone %>
</p>

<p>
  <strong>User:</strong>
  <%= @voter.user %>
</p>

<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>